name: Ceedling Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: cppcheck
      uses: deep5050/cppcheck-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN}}
        force: enable
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Ruby
      run: sudo apt-get install ruby

    - name: Setup Ceedling
      run: sudo gem install ceedling
        
    - name: Test
      run: ceedling
      
